question_data = [
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Leonardo DiCaprio won an Oscar for Best Actor in 'The Aviator'.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "The Republic of Malta is the smallest microstate worldwide.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "The book 1984 was published in 1949.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Mathematics", "type": "boolean", "difficulty": "easy",
     "question": "The 'Squaring the Circle' problem is solvable.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
     "question": "You can legally drink alcohol while driving in Mississippi.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The ultimate phrase used by Pharah from Overwatch is: 'Justice rains from above!'",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "There are no deserts in Europe.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "Stephen Chbosky wrote the book 'The Perks of Being A Wallflower'.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The alternative rock band, They Might Be Giants, released their album 'Flood' in 1990. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Comics", "type": "boolean", "difficulty": "easy",
     "question": "The 'Pepe' meme originated from a comic drawn by Matt Furie called 'Boys Club'.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The song 'Stronger Than You' is a single by Estelle, who played Garnet in Steven Universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "In the movie The Revenant, DiCaprio character hunts down the killer of his son.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In Pokemon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "&quot;Minions&quot; was released on the June 10th, 2015.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In 'Need for Speed: Porsche Unleashed', the player can only drive cars manufactured by Porsche.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
     "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the video game 'Splatoon', "
                 "the playable characters were originally going to be rabbits instead of squids.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Each piece in Tetris is called a tetris.", "correct_answer": "False",
     "incorrect_answers": ["True"]}
]
